version: "2.1"
services:
# MySQL database
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql/datadir:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.19.0.2
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "123456"

# NGINX
  nginx:
    image: nginx:latest
    volumes:
      - ./sites:/var/www/html
      - ./volumes/nginx/logs:/var/log/nginx
      - ./configs/nginx/virtualhosts:/etc/nginx/sites-enabled
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      default:
        ipv4_address: 172.19.0.3
    environment:
      TZ: "America/Sao_Paulo"
    links:
      - php

# PHP 7.1
  php:
    build:
      context: ./configs/docker/images/php
      dockerfile: ./Dockerfile
    volumes:
      - ./sites:/var/www/html
      - ./volumes/php/logs:/var/log
      - ./configs/php/fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      default:
        ipv4_address: 172.19.0.4
    environment:
      TZ: "America/Sao_Paulo"
    links:
      - mysql
    extends:
      file: virtualhosts.yml
      service: php

# Networks
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/24
