version: "2"
services:
# MySQL database
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ~/sites/docker/mysql/datadir:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.19.0.2
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "123456"

# NGINX
  webserver:
    image: nginx:latest
    # ports:
    #   - "8080:80"
    volumes:
      - ~/sites/html:/var/www/html
      - ~/sites/logs/nginx:/var/log/nginx
      - ~/sites/virtualhosts:/etc/nginx/sites-enabled
      - ~/sites/nginx.conf:/etc/nginx/nginx.conf
    networks:
      default:
        ipv4_address: 172.19.0.3
    environment:
      TZ: "America/Sao_Paulo"
    links:
      - php

# PHP 7.1
  php:
    image: php:7.1-fpm
    # ports:
    #   - "8080:80"
    volumes:
      - ~/sites/logs/fpm:/var/log
      - ~/sites/html:/var/www/html
      - ~/sites/fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      default:
        ipv4_address: 172.19.0.4
    environment:
      TZ: "America/Sao_Paulo"
    extra_hosts:
      - chromatox.localhost:172.19.0.3
      - jltransportes.localhost:172.19.0.3

# Networks
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/24
