version: "2.1"
services:
# Database
  database:
    extends:
      file: database.yml
      # service: mysql
      service: pgsql
    networks:
      default:
        ipv4_address: 172.19.0.2
    environment:
      TZ: "America/Sao_Paulo"

# Webserver
  webserver:
    extends:
      file: webserver.yml
      # service: nginx
      service: apache
    networks:
      default:
        ipv4_address: 172.19.0.3
    environment:
      TZ: "America/Sao_Paulo"
    links:
      - php

# PHP 7.1
  php:
    build:
      context: ./configs/docker/images/php
      dockerfile: ./Dockerfile
    volumes:
      - ./sites:/var/www/html
      - ./volumes/php/logs:/var/log
      - ./configs/php/fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      default:
        ipv4_address: 172.19.0.4
    environment:
      TZ: "America/Sao_Paulo"
    links:
      - database
    extends:
      file: virtualhosts.yml
      service: php

# Networks
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/24
