version: "2.1"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./sites:/var/www/html
      - ./volumes/nginx/logs:/var/log/nginx
      - ./configs/nginx/virtualhosts:/etc/nginx/sites-enabled
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
  apache:
    build:
      context: ./configs/docker/images/apache
      dockerfile: ./Dockerfile
    volumes:
      - ./sites:/var/www/html
      - ./volumes/apache/logs:/usr/local/apache2/logs
      - ./configs/apache/virtualhosts:/usr/local/apache2/conf/sites-enabled
      - ./configs/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
